graph TD
    A[Input: shape=1] --> B[Conv2D: out_channels=32, kernel_size=3]
    B --> C[BatchNorm: num_features=32]
    C --> D[ReLU]
    D --> E[MaxPool2D: 2]
    E --> F[Conv2D: out_channels=64, kernel_size=3]
    F --> G[BatchNorm: num_features=64]
    G --> H[ReLU]
    H --> I[MaxPool2D: 2]
    I --> J[Flatten]
    J --> K[Linear: 128]
    K --> L[ReLU]
    L --> M[Dropout: 0.5]
    M --> N[Linear: 10]
    N --> O[Softmax]
